experiment:
  type: single
  method: [none, sequential]
  objective: twitter
  noise: joint
  A_limits: [0.25, 0.9]
  X_limits: [-0.25, 1.0]
  num_samples: 405
  num_train_samples: 50
  num_A_samples: 80
  seed: 5
  fixed_kernel: true
  show_plots: true
  show_hessian: false
  kernel:
  - type: 'rbf'
    length_scale: 0.1
  - type: white
    noise_level: 0.01
