experiment:
  type: single
  method: sequential
  objective: twitter
  noise: joint
  A_limits: [0.25, 1.0]
  X_limits: [-0.25, 1.0]
  num_samples: 405
  num_train_samples: 50
  num_A_samples: 80
  seed: 5
  fixed_kernel: false
  show_plots: true
  show_hessian: false
  calculate_convexity: true
  kernel:
  - type: 'rbf'
    length_scale: 0.1
  - type: white
    noise_level: 0.0002

