bayes_opt:
  type: comparative
  objective: botorch_ackley_6d
  n_seeds: 10
  init_points: 10
  n_iter: 50
  acquisition: qUpperConfidenceBound
  acquisition_params:
    kappa: 2.576
  save_results: true
  plot_results: true
  results_path: botorch_ackley_6d_noisy_statistical.txt
  sample_optimization:
    # algorithm: [none, joint, warped_gp, heteroscedastic_gp, relevance_pursuit, modulating_surrogates]
    algorithm: [none, joint, warped_gp, relevance_pursuit]
    method: sequential 
    min_samples: 5
  kernel:
    - type: matern
      nu: 2.5
      length_scale: 0.25           
  alpha: 0.1
  perturbation:
    type: constant
    probability: 0.1
    value: -100.0
